### ISSUE TITLE
ocamlrun location

### ISSUE THREAD

**Issue by brianthehughes** [vimanuelt/package_log_viewer#1]
1. Initially missing

ocaml-lablgtk3-3.1.5           Objective Caml interface to GTK 3.x

2.root@d501 /h/b/package_log_viewer (main)# which ocamlrun
/usr/local/bin/ocamlrun

root@d501 /h/b/package_log_viewer (main)# /usr/local/bin/plv
exec: Failed to execute process '/usr/local/bin/plv': The file specified the interpreter '/home/a5/.opam/4.14.0/bin/ocamlrun', which is not an executable command.

3. Okay, let me make clean. and make

root@d501 /h/b/package_log_viewer (main)# make all
ocamlfind ocamlc -thread -package lablgtk3,str -linkpkg -o plv plv.ml
File "plv.ml", line 1:
Error: I/O error: dllcairo_stubs.so: No such file or directory
*** Error code 2

Stop.
make: stopped in /home/brian/package_log_viewer

That's as far as I got with plv. I suspect I'm missing a package somewhere. Possibly related the to the overlapping nature of Package Repository Selector.

**Comment by vimanuelt** [comment]
I've updated the Makefile to include the missing dependencies. Thanks for the feedback.

https://github.com/vimanuelt/package_log_viewer/commit/aaef32f7694f772055afa656a4f4f4e5f6d0dda8

**Comment by brianthehughes** [comment]
Thanks for the updates.
